import type { BossesArray } from '../types/Bosses.types';

import { REGIONS } from './Regions';
import { SPAWN_RATE, SPAWN_TYPE } from './Spawns';

export const allBosses: BossesArray = [
  {
    name: 'Wolf King',
    region: REGIONS.CARACAZOR,
    spawnTime: 1,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Corrupted Treant',
    region: REGIONS.CARACAZOR,
    spawnTime: 2,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Mountain Giant',
    region: REGIONS.CARACAZOR,
    spawnTime: 2,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Shield Maiden',
    region: REGIONS.CARACAZOR,
    spawnTime: 2,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Grasslands Giant',
    region: REGIONS.CARACAZOR,
    spawnTime: 14,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Stone Zephyr',
    region: REGIONS.NAVARRA,
    spawnTime: 7,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Dustwind Champ',
    region: REGIONS.NAVARRA,
    spawnTime: 7,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Sunpiercer',
    region: REGIONS.NAVARRA,
    spawnTime: 7,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Harpy Queen',
    region: REGIONS.NAVARRA,
    spawnTime: 18,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Kolbold Forman',
    region: REGIONS.GNOLL,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Ston Zephyr',
    region: REGIONS.GNOLL,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Flame Giant (North)',
    region: REGIONS.GNOLL,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Flame Giant (South)',
    region: REGIONS.GNOLL,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Greenwarden',
    region: REGIONS.GNOLL,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Bashal',
    region: REGIONS.GNOLL,
    spawnTime: 25,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Frost Giant',
    region: REGIONS.RUINS,
    spawnTime: 12,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Black Knight',
    region: REGIONS.RUINS,
    spawnTime: 12,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Revived Murderer',
    region: REGIONS.RUINS,
    spawnTime: 12,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Noxious Ghoul',
    region: REGIONS.RUINS,
    spawnTime: 12,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Cyclops',
    region: REGIONS.RUINS,
    spawnTime: 25,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Spider Queen',
    region: REGIONS.RUINS,
    spawnTime: 25,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Mecha Boxer',
    region: REGIONS.TIMELESS,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Emissary of Flames',
    region: REGIONS.TIMELESS,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Skaniss',
    region: REGIONS.TIMELESS,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Osis',
    region: REGIONS.TIMELESS,
    spawnTime: 4,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.HOURS,
  },
  {
    name: 'Volcanic Wyvern',
    region: REGIONS.ZENKALA,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Thunder Wyvern',
    region: REGIONS.ZENKALA,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Stonescale Wyvern',
    region: REGIONS.ZENKALA,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Soulraiser',
    region: REGIONS.SPERIOS,
    spawnTime: 9,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Roughscar Boar',
    region: REGIONS.KANNUS_M,
    spawnTime: 2,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: '2H Wyvern',
    region: REGIONS.KANNUS_M,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Bone Dragon',
    region: REGIONS.KANNUS_M,
    spawnTime: 4,
    spawnType: SPAWN_TYPE.WEEKLY,
    spawnRate: SPAWN_RATE.HOURLY,
  },
  {
    name: 'General of the Fallen Kingdom',
    region: REGIONS.KANNUS_V,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Herbati Champ',
    region: REGIONS.KANNUS_V,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Stone Zephyr',
    region: REGIONS.BEORAN,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Knight of Regret',
    region: REGIONS.BEORAN,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Mercenary Kynix',
    region: REGIONS.BEORAN,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Steelspine Pagar Warrior',
    region: REGIONS.OSTIUM,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Dragonnewt Blademaster',
    region: REGIONS.OSTIUM,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Kobold Foreman',
    region: REGIONS.OSTIUM,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Bloodband Raider',
    region: REGIONS.OSTIUM,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'The Pale Strider',
    region: REGIONS.OSTIUM,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Revived Murderer',
    region: REGIONS.EIDOLON,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Wandering Mountain Giant',
    region: REGIONS.EIDOLON,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Flame Giant',
    region: REGIONS.EIDOLON,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'Ursa',
    region: REGIONS.DUNES,
    spawnTime: 4,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.HOURS,
  },
  {
    name: 'The Canyon Cannibal',
    region: REGIONS.DUNES,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
  {
    name: 'The Pale Strider',
    region: REGIONS.DUNES,
    spawnTime: 15,
    spawnType: SPAWN_TYPE.DAILY,
    spawnRate: SPAWN_RATE.MINUTES,
  },
];
